server:
  port: 8081

spring:
  application:
    name: uniqlo-men-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssh?useUnicode=true&characterEncoding=utf-8
    username: root
    password:

mybatis:
  type-aliases-package: controller.jk.model
  mapper-locations: classpath:mybatis/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/